### ISSUE TITLE
Could not create VM

### ISSUE THREAD

**Issue by ekrylovich** [nagaseshadri/puppet-vagrant-oc11.1#1]
Hello, trying to create VM using your project, but facing next issue:
**d:\vagrant-projects\puppet-vagrant-oc11.1-master>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'atg'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: OC11.1VM
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8006 (guest) => 8006 (host) (adapter 1)
    default: 15000 (guest) => 15000 (host) (adapter 1)
    default: 15002 (guest) => 15002 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...**

repeated many times,

then
**Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.**

I'm using last vagrant 1.8.5 and last VirtualBox-5.1.4

Could you advice me something to solve the issue?

**Comment by nagaseshadri** [comment]
-> Try removing the current box thats being provisioned
-> Remove and add the box again to Vagrant
-> Try to clone the project afresh into a new folder and then try vagrant up and see if it works...update paths in config accordingly, if need be

**Comment by ekrylovich** [comment]
adding in VAgrant file:
config.ssh.insert_key = false
helped me

**Comment by ekrylovich** [comment]
Real cause of the issue is bug in the latest version of vagrant - 1.8.5
https://github.com/mitchellh/vagrant/issues/7610
another solution is to downgrade vagrant
I downgrade it to 1.8.0 and for this version of vagrant you also need to downgrade VirtualBox at least to 5.0.10. And it works for me.
